In [2]:
from google.colab import drive

drive.mount('/content/drive')
path = '/content/drive/MyDrive/Datasheet/movies_metadata.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd

df = pd.read_csv(path)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

/tmp/ipykernel_25568/3766738840.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [4]:
feature = ['title','genres','overview','tagline','belongs_to_collection']
df_feature = df[feature].copy()

In [5]:
df_feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  45460 non-null  object
 1   genres                 45466 non-null  object
 2   overview               44512 non-null  object
 3   tagline                20412 non-null  object
 4   belongs_to_collection  4494 non-null   object
dtypes: object(5)
memory usage: 1.7+ MB

**Data Cleaning**

In [6]:
df_feature.head()

                         title  ...                              belongs_to_collection
0                    Toy Story  ...  {'id': 10194, 'name': 'Toy Story Collection', ...
1                      Jumanji  ...                                                NaN
2             Grumpier Old Men  ...  {'id': 119050, 'name': 'Grumpy Old Men Collect...
3            Waiting to Exhale  ...                                                NaN
4  Father of the Bride Part II  ...  {'id': 96871, 'name': 'Father of the Bride Col...

[5 rows x 5 columns]

In [7]:
df_feature['genres'].apply(type).value_counts(dropna=False)

genres
<class 'str'>    45466
Name: count, dtype: int64

In [8]:
df_feature['belongs_to_collection'].apply(type).value_counts(dropna=False)

belongs_to_collection
<class 'float'>    40972
<class 'str'>       4494
Name: count, dtype: int64

In [9]:
import ast

def get_extraction_name(x):
  if isinstance(x, float):
    return ""

  # Proses ektrasi name "kunci"
  try:
    data_collection = ast.literal_eval(x)
    return data_collection['name']
  except (ValueError, SyntaxError, KeyError, TypeError):
    return ""

In [10]:
df_feature['genres'] = df_feature['genres'].apply(lambda x: " ".join([i['name']for i in ast.literal_eval(x)]))

In [11]:
df_feature['belongs_to_collection'] = df_feature['belongs_to_collection'].apply(get_extraction_name)

In [12]:
df_feature.head()

                         title  ...           belongs_to_collection
0                    Toy Story  ...            Toy Story Collection
1                      Jumanji  ...
2             Grumpier Old Men  ...       Grumpy Old Men Collection
3            Waiting to Exhale  ...
4  Father of the Bride Part II  ...  Father of the Bride Collection

[5 rows x 5 columns]

In [13]:
df_feature.duplicated(subset=['title','genres','overview','tagline'], keep='first').sum()

np.int64(32)

In [14]:
dup_suspect = df_feature[df_feature.duplicated(subset=['title','genres','overview','tagline'], keep=False)].sort_values(by=['title'])

In [15]:
pd.set_option('display.max_rows',None)
display(dup_suspect[['title','genres','overview','tagline','belongs_to_collection']])

                                             title  ... belongs_to_collection
32791                                    12 Chairs  ...
32777                                    12 Chairs  ...
15074                           A Farewell to Arms  ...
949                             A Farewell to Arms  ...
21116                         A Place at the Table  ...
2564                          A Place at the Table  ...
22733                     A Streetcar Named Desire  ...
22734                     A Streetcar Named Desire  ...
11155                                   Black Gold  ...
20843                                   Black Gold  ...
16764                                     Blackout  ...
13375                                     Blackout  ...
13261                                     Blackout  ...
23044                                  Brotherhood  ...
17229                                  Brotherhood  ...
10419                                       Bubble  ...
12066                                       Bubble  ...
4356                          Camille Claudel 1915  ...
23534                         Camille Claudel 1915  ...
33184                        Cemetery of Splendour  ...
40040                        Cemetery of Splendour  ...
5130                                 Clockstoppers  ...
33743                                Clockstoppers  ...
5865               Confessions of a Dangerous Mind  ...
33826              Confessions of a Dangerous Mind  ...
22151                             Days of Darkness  ...
14000                             Days of Darkness  ...
24844                                         Deal  ...
14012                                         Deal  ...
24164                                Force Majeure  ...
45265                                Force Majeure  ...
29374                                    King Lear  ...
15702                                    King Lear  ...
7345                                   Le Samouraï  ...
9165                                   Le Samouraï  ...
28860               Nana, the True Key of Pleasure  ...
13603               Nana, the True Key of Pleasure  ...
15765                                      Offside  ...
11342                                      Offside  ...
5535   Pokémon 4Ever: Celebi - Voice of the Forest  ...    Pokémon Collection
44826  Pokémon 4Ever: Celebi - Voice of the Forest  ...    Pokémon Collection
4114                 Pokémon: Spell of the Unknown  ...    Pokémon Collection
44821                Pokémon: Spell of the Unknown  ...    Pokémon Collection
5710                               Rich and Famous  ...
20899                              Rich and Famous  ...
40276                         Seven Years Bad Luck  ...
13946                         Seven Years Bad Luck  ...
19925                                 The Congress  ...
21854                                 The Congress  ...
9576                      The Phantom of the Opera  ...
26625                     The Phantom of the Opera  ...
1465                                   The Promise  ...
676                                    The Promise  ...
21165                                  The Tempest  ...
19890                                  The Tempest  ...
16167                                   The Viking  ...
38871                                   The Viking  ...
9327                                   The Warrior  ...
8068                                   The Warrior  ...
13220             Why We Fight: Divide and Conquer  ...          Why We Fight
35798             Why We Fight: Divide and Conquer  ...          Why We Fight
838                                           Wife  ...
30001                                         Wife  ...

[63 rows x 5 columns]

In [16]:
df_feature = df_feature.drop_duplicates(subset=['title','genres','overview'])

In [17]:
df_feature.duplicated(subset=['title','genres','overview','tagline']).sum()

np.int64(0)

In [18]:
df_feature.duplicated().sum()

np.int64(0)

In [19]:
display(dup_suspect[['title','genres','overview','tagline','belongs_to_collection']])

                                             title  ... belongs_to_collection
32791                                    12 Chairs  ...
32777                                    12 Chairs  ...
15074                           A Farewell to Arms  ...
949                             A Farewell to Arms  ...
21116                         A Place at the Table  ...
2564                          A Place at the Table  ...
22733                     A Streetcar Named Desire  ...
22734                     A Streetcar Named Desire  ...
11155                                   Black Gold  ...
20843                                   Black Gold  ...
16764                                     Blackout  ...
13375                                     Blackout  ...
13261                                     Blackout  ...
23044                                  Brotherhood  ...
17229                                  Brotherhood  ...
10419                                       Bubble  ...
12066                                       Bubble  ...
4356                          Camille Claudel 1915  ...
23534                         Camille Claudel 1915  ...
33184                        Cemetery of Splendour  ...
40040                        Cemetery of Splendour  ...
5130                                 Clockstoppers  ...
33743                                Clockstoppers  ...
5865               Confessions of a Dangerous Mind  ...
33826              Confessions of a Dangerous Mind  ...
22151                             Days of Darkness  ...
14000                             Days of Darkness  ...
24844                                         Deal  ...
14012                                         Deal  ...
24164                                Force Majeure  ...
45265                                Force Majeure  ...
29374                                    King Lear  ...
15702                                    King Lear  ...
7345                                   Le Samouraï  ...
9165                                   Le Samouraï  ...
28860               Nana, the True Key of Pleasure  ...
13603               Nana, the True Key of Pleasure  ...
15765                                      Offside  ...
11342                                      Offside  ...
5535   Pokémon 4Ever: Celebi - Voice of the Forest  ...    Pokémon Collection
44826  Pokémon 4Ever: Celebi - Voice of the Forest  ...    Pokémon Collection
4114                 Pokémon: Spell of the Unknown  ...    Pokémon Collection
44821                Pokémon: Spell of the Unknown  ...    Pokémon Collection
5710                               Rich and Famous  ...
20899                              Rich and Famous  ...
40276                         Seven Years Bad Luck  ...
13946                         Seven Years Bad Luck  ...
19925                                 The Congress  ...
21854                                 The Congress  ...
9576                      The Phantom of the Opera  ...
26625                     The Phantom of the Opera  ...
1465                                   The Promise  ...
676                                    The Promise  ...
21165                                  The Tempest  ...
19890                                  The Tempest  ...
16167                                   The Viking  ...
38871                                   The Viking  ...
9327                                   The Warrior  ...
8068                                   The Warrior  ...
13220             Why We Fight: Divide and Conquer  ...          Why We Fight
35798             Why We Fight: Divide and Conquer  ...          Why We Fight
838                                           Wife  ...
30001                                         Wife  ...

[63 rows x 5 columns]

In [20]:
df_feature.isna().sum()

title                        6
genres                       0
overview                   954
tagline                  25033
belongs_to_collection        0
dtype: int64

In [21]:
missing_overview_tagline = df_feature[df_feature['overview'].isna() | df_feature['tagline'].isna()]
display(missing_overview_tagline[['title','genres','overview','tagline']].head(5))

                          title  ... tagline
0                     Toy Story  ...     NaN
11  Dracula: Dead and Loving It  ...     NaN
27                   Persuasion  ...     NaN
32             Wings of Courage  ...     NaN
35             Dead Man Walking  ...     NaN

[5 rows x 4 columns]

In [22]:
df_feature.loc[:, 'overview'] = df_feature['overview'].fillna("")
df_feature.loc[:, 'tagline'] = df_feature['tagline'].fillna("")

In [23]:
df_feature.isna().sum()

title                    6
genres                   0
overview                 0
tagline                  0
belongs_to_collection    0
dtype: int64

In [24]:
missing_title = df_feature[df_feature['title'].isna()]
display(missing_title)

      title  ...        belongs_to_collection
19729   NaN  ...
19730   NaN  ...
29502   NaN  ...  Mardock Scramble Collection
29503   NaN  ...
35586   NaN  ...
35587   NaN  ...

[6 rows x 5 columns]

In [25]:
df_feature = df_feature.dropna(subset=['title'])

In [26]:
df_feature.isna().sum()

title                    0
genres                   0
overview                 0
tagline                  0
belongs_to_collection    0
dtype: int64

In [27]:
df_feature.shape

(45428, 5)

In [28]:
df_feature.head()

                         title  ...           belongs_to_collection
0                    Toy Story  ...            Toy Story Collection
1                      Jumanji  ...
2             Grumpier Old Men  ...       Grumpy Old Men Collection
3            Waiting to Exhale  ...
4  Father of the Bride Part II  ...  Father of the Bride Collection

[5 rows x 5 columns]

**Text Preprocessing**

In [29]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize

text_features = [
    'genres',
    'overview',
    'tagline',
    'belongs_to_collection'
]
content_df = df_feature[
    ['title'] + text_features
].copy()

In [30]:
# Hapus spasi berlebihan
for col in text_features:
  content_df[col] = content_df[col].str.strip()
content_df.head(10)

                         title  ...           belongs_to_collection
0                    Toy Story  ...            Toy Story Collection
1                      Jumanji  ...
2             Grumpier Old Men  ...       Grumpy Old Men Collection
3            Waiting to Exhale  ...
4  Father of the Bride Part II  ...  Father of the Bride Collection
5                         Heat  ...
6                      Sabrina  ...
7                 Tom and Huck  ...
8                 Sudden Death  ...
9                    GoldenEye  ...           James Bond Collection

[10 rows x 5 columns]

In [32]:
tfidf_matrices = {}
for col in text_features:
  vectorizer = TfidfVectorizer(
      stop_words="english",
      max_features=5000,
      dtype=np.float32
  )

  tfidf_matrices[col] = vectorizer.fit_transform(content_df[col])
  print(
      f"{col} : {tfidf_matrices[col].shape}, "
      f"non-zero values: {tfidf_matrices[col].nnz:,}"
  )

genres : (45428, 22), non-zero values: 94,811
overview : (45428, 5000), non-zero values: 914,184
tagline : (45428, 5000), non-zero values: 75,286
belongs_to_collection : (45428, 2276), non-zero values: 12,372

In [68]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def content_based_recommender(
    movie_title, data, tfidf_matrices, top_n=10
):
    weights = {
        "genres": 0.30,
        "overview": 0.45,
        "tagline": 0.10,
        "belongs_to_collection": 0.15
    }

    # Cari posisi baris film, bukan label indeks DataFrame
    titles = data["title"].fillna("").str.casefold().to_numpy()
    matches = np.flatnonzero(titles == movie_title.casefold())

    if len(matches) == 0:
        print(f"Film '{movie_title}' tidak ditemukan.")
        return data.iloc[0:0].copy()

    movie_idx = int(matches[0])
    scores = np.zeros(len(data), dtype=np.float32)

    for col, weight in weights.items():
        matrix = tfidf_matrices[col]

        if matrix.shape[0] != len(data):
            raise ValueError(
                f"Jumlah baris matriks {col} tidak sama "
                "dengan jumlah baris data."
            )

        similarity = cosine_similarity(
            matrix[movie_idx], matrix
        ).ravel()

        scores += weight * similarity.astype(np.float32)

    # Keluarkan film input dari hasil rekomendasi
    scores[movie_idx] = -1

    top_n = min(top_n, len(data) - 1)
    top_indices = np.argsort(scores)[-top_n:][::-1]

    results = data.iloc[top_indices].copy()
    results["similarity_score"] = scores[top_indices]

    return results.reset_index(drop=True)

In [64]:
recommendations = content_based_recommender(
    movie_title="Toy Story",
    data=content_df,
    tfidf_matrices=tfidf_matrices,
    top_n=10
)

In [65]:
recommendations[
    [
        'title',
        'genres',
        'belongs_to_collection',
        'similarity_score'
    ]
]

                                   title  ... similarity_score
0                            Toy Story 3  ...         0.665822
1                            Toy Story 2  ...         0.597536
2            Andy Hardy's Blonde Trouble  ...         0.362152
3                      Hawaiian Vacation  ...         0.355225
4                         Monsters, Inc.  ...         0.350465
5                             Free Birds  ...         0.344598
6        Garfield: A Tail of Two Kitties  ...         0.328715
7                               The Wild  ...         0.328301
8  Monster High: Welcome to Monster High  ...         0.327672
9        Rudolph, the Red-Nosed Reindeer  ...         0.325905

[10 rows x 4 columns]

In [47]:
recommendations = content_based_recommender(
    movie_title="The Shawshank Redemption",
    data=content_df,
    tfidf_matrices=tfidf_matrices,
    top_n=10
)

display(
    recommendations[
        ["title", "genres", "belongs_to_collection", "similarity_score"]
    ]
)

                  title       genres belongs_to_collection  similarity_score
0           Brute Force  Crime Drama                                0.418596
1                Breath  Crime Drama                                0.398099
2  Duffy of San Quentin  Drama Crime                                0.393072
3              Brubaker  Crime Drama                                0.387561
4               Variety  Drama Crime                                0.386127
5        Cool Hand Luke  Crime Drama                                0.383035
6        Convict's Code  Crime Drama                                0.381893
7             A Prophet  Crime Drama                                0.381181
8  The Domino Principle  Drama Crime                                0.379429
9        House of Women  Crime Drama                                0.374816

In [66]:
movie_title = "The Shawshank Redemption"

# Tampilkan sinopsis film input
display(
    content_df.loc[
        content_df["title"].str.casefold() == movie_title.casefold(),
        ["title", "genres", "overview"]
    ]
)

                        title  ...                                           overview
314  The Shawshank Redemption  ...  Framed in the 1940s for the double murder of h...

[1 rows x 3 columns]

In [52]:
# Tampilkan sinopsis hasil rekomendasi
display(
    recommendations[
        ["title", "genres", "overview", "similarity_score"]
    ]
)

                  title  ... similarity_score
0           Brute Force  ...         0.418596
1                Breath  ...         0.398099
2  Duffy of San Quentin  ...         0.393072
3              Brubaker  ...         0.387561
4               Variety  ...         0.386127
5        Cool Hand Luke  ...         0.383035
6        Convict's Code  ...         0.381893
7             A Prophet  ...         0.381181
8  The Domino Principle  ...         0.379429
9        House of Women  ...         0.374816

[10 rows x 4 columns]

In [67]:
display(
    (content_based_recommender(
        'The Dark Knight',
        content_df,
        tfidf_matrices,
        top_n=10
    )[
        ['title','genres','similarity_score']
    ])
)

                      title                       genres  similarity_score
0     The Dark Knight Rises  Action Crime Drama Thriller          0.576426
1             Batman Begins           Action Crime Drama          0.489785
2                  Ricochet        Action Crime Thriller          0.361820
3  Mesrine: Killer Instinct  Drama Action Thriller Crime          0.355774
4            Get the Gringo  Action Thriller Crime Drama          0.344987
5       Running Out of Time  Drama Action Thriller Crime          0.344874
6                    Hitman  Action Crime Drama Thriller          0.341553
7                  S.W.A.T.        Action Thriller Crime          0.341496
8  Mesrine: Public Enemy #1  Action Thriller Crime Drama          0.338834
9                       F/X        Crime Thriller Action          0.336366

In [69]:
test_movies = [
    'The Dark Knight',
    'Finding Nemo',
    'The GodFather',
    'Titanic',
    'Toy Story',
    'The Conjuring',
    'Home Alone',
    'The Matrix',
    'Minions',
    'The Shawshank Redemption'
]

In [70]:
for movies in test_movies:
  print(f"\n{'=' * 80}")
  print(f"REKOMENDASI UNTUK : {movies}")
  print(f"{'=' * 80}")
  result = content_based_recommender(
      movie_title=movies,
      data=content_df,
      tfidf_matrices=tfidf_matrices,
      top_n = 10
  )

  display(result[['title','genres','belongs_to_collection','similarity_score']])

================================================================================
REKOMENDASI UNTUK : The Dark Knight
================================================================================

                      title  ... similarity_score
0     The Dark Knight Rises  ...         0.576426
1             Batman Begins  ...         0.489785
2                  Ricochet  ...         0.361820
3  Mesrine: Killer Instinct  ...         0.355774
4            Get the Gringo  ...         0.344987
5       Running Out of Time  ...         0.344874
6                    Hitman  ...         0.341553
7                  S.W.A.T.  ...         0.341496
8  Mesrine: Public Enemy #1  ...         0.338834
9                       F/X  ...         0.336366

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : Finding Nemo
================================================================================

                                       title  ... similarity_score
0                            Back To The Sea  ...         0.402791
1                               Finding Dory  ...         0.390276
2                      The Reef 2: High Tide  ...         0.386646
3  The Secret of NIMH 2: Timmy to the Rescue  ...         0.350563
4                                       Ozzy  ...         0.350451
5                          The Rugrats Movie  ...         0.348699
6                                   Paperman  ...         0.345272
7   VeggieTales: Where's God When I'm Scared  ...         0.343677
8                         The Littlest Angel  ...         0.343335
9                                   Bambi II  ...         0.340213

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : The GodFather
================================================================================

                     title  ... similarity_score
0   The Godfather: Part II  ...         0.526293
1  The Godfather: Part III  ...         0.413367
2                 Election  ...         0.402825
3            Live by Night  ...         0.387092
4             I Am the Law  ...         0.379660
5                Adulthood  ...         0.360016
6                 The Boys  ...         0.359150
7            South Central  ...         0.357652
8               Once Again  ...         0.357619
9        One Hundred Steps  ...         0.354390

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : Titanic
================================================================================

                title  ... similarity_score
0                Fida  ...         0.360214
1  Return to Paradise  ...         0.356591
2  Cruel Intentions 3  ...         0.342926
3        Dustbin Baby  ...         0.340161
4   My Summer of Love  ...         0.334671
5              Sylvia  ...         0.333721
6          Blown Away  ...         0.331849
7     Ismael's Ghosts  ...         0.330480
8                Fear  ...         0.326102
9                 Cal  ...         0.324205

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : Toy Story
================================================================================

                                   title  ... similarity_score
0                            Toy Story 3  ...         0.665822
1                            Toy Story 2  ...         0.597536
2            Andy Hardy's Blonde Trouble  ...         0.362152
3                      Hawaiian Vacation  ...         0.355225
4                         Monsters, Inc.  ...         0.350465
5                             Free Birds  ...         0.344598
6        Garfield: A Tail of Two Kitties  ...         0.328715
7                               The Wild  ...         0.328301
8  Monster High: Welcome to Monster High  ...         0.327672
9        Rudolph, the Red-Nosed Reindeer  ...         0.325905

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : The Conjuring
================================================================================

                              title  ... similarity_score
0                   The Conjuring 2  ...         0.555488
1                  Grave Encounters  ...         0.387277
2  Paranormal Activity: Tokyo Night  ...         0.381601
3                          The Evil  ...         0.380134
4             Die! Die! My Darling!  ...         0.377416
5                 Babysitter Wanted  ...         0.376594
6                        Jessabelle  ...         0.375932
7                          The Ward  ...         0.374402
8                    The Apparition  ...         0.373420
9                      The Darkness  ...         0.372752

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : Home Alone
================================================================================

                            title  ... similarity_score
0  Home Alone 2: Lost in New York  ...         0.475209
1                    Home Alone 3  ...         0.474771
2                    Home Alone 4  ...         0.452745
3   Home Alone: The Holiday Heist  ...         0.429344
4         The Great Gilly Hopkins  ...         0.393301
5                      Uncle Buck  ...         0.373512
6            Family Ties Vacation  ...         0.373486
7                       Beethoven  ...         0.372652
8                Are We Done Yet?  ...         0.364812
9         Like Mike 2: Streetball  ...         0.363928

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : The Matrix
================================================================================

                      title  ... similarity_score
0       The Matrix Reloaded  ...         0.400092
1    The Matrix Revolutions  ...         0.389537
2       Battle of the Stars  ...         0.385002
3                 Road Wars  ...         0.365762
4               The Phantom  ...         0.365544
5                 Earthfall  ...         0.362926
6             Circuitry Man  ...         0.362143
7       V: The Final Battle  ...         0.362049
8  The Day the Sky Exploded  ...         0.358390
9           Prince of Space  ...         0.356508

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : Minions
================================================================================

                                               title  ... similarity_score
0                                    Despicable Me 2  ...         0.571038
1                                    Despicable Me 3  ...         0.443261
2                                      Despicable Me  ...         0.439603
3                                             Banana  ...         0.408550
4                                      Mower Minions  ...         0.351468
5                                     Wreck-It Ralph  ...         0.344241
6                       The Curse of the Were-Rabbit  ...         0.342516
7              Pokémon: Giratina and the Sky Warrior  ...         0.341544
8  Dragon Ball Z: Broly - The Legendary Super Saiyan  ...         0.340614
9                                          Dino Time  ...         0.340352

[10 rows x 4 columns]

================================================================================
REKOMENDASI UNTUK : The Shawshank Redemption
================================================================================

                  title       genres belongs_to_collection  similarity_score
0           Brute Force  Crime Drama                                0.418596
1                Breath  Crime Drama                                0.398099
2  Duffy of San Quentin  Drama Crime                                0.393072
3              Brubaker  Crime Drama                                0.387561
4               Variety  Drama Crime                                0.386127
5        Cool Hand Luke  Crime Drama                                0.383035
6        Convict's Code  Crime Drama                                0.381893
7             A Prophet  Crime Drama                                0.381181
8  The Domino Principle  Drama Crime                                0.379429
9        House of Women  Crime Drama                                0.374816

In [71]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

movie_title = "The Dark Knight"

weights = {
    "genres": 0.30,
    "overview": 0.45,
    "tagline": 0.10,
    "belongs_to_collection": 0.15
}

matches = np.flatnonzero(
    content_df["title"].str.casefold().to_numpy()
    == movie_title.casefold()
)

if len(matches) == 0:
    print(f"Film '{movie_title}' tidak ditemukan.")
else:
    movie_idx = int(matches[0])
    contributions = {}

    for col, weight in weights.items():
        matrix = tfidf_matrices[col]
        similarity = cosine_similarity(
            matrix[movie_idx], matrix
        ).ravel()

        contributions[col] = weight * similarity

    diagnostic = content_df[
        ["title", "genres"]
    ].copy()

    for col, values in contributions.items():
        diagnostic[f"{col}_contribution"] = values

    contribution_cols = [
        f"{col}_contribution" for col in weights
    ]

    diagnostic["total_score"] = diagnostic[
        contribution_cols
    ].sum(axis=1)

    diagnostic = diagnostic.drop(index=content_df.index[movie_idx])

    display(
        diagnostic.nlargest(10, "total_score").reset_index(drop=True)
    )

                      title  ... total_score
0     The Dark Knight Rises  ...    0.576426
1             Batman Begins  ...    0.489785
2                  Ricochet  ...    0.361820
3  Mesrine: Killer Instinct  ...    0.355774
4            Get the Gringo  ...    0.344987
5       Running Out of Time  ...    0.344874
6                    Hitman  ...    0.341553
7                  S.W.A.T.  ...    0.341496
8  Mesrine: Public Enemy #1  ...    0.338834
9                       F/X  ...    0.336366

[10 rows x 7 columns]

## Evaluasi Hasil Rekomendasi

### Tujuan Evaluasi

Evaluasi dilakukan untuk mengamati kemampuan sistem dalam merekomendasikan film berdasarkan kemiripan konten. Pengujian menggunakan beberapa film dari genre dan koleksi yang berbeda untuk melihat apakah rekomendasi yang dihasilkan relevan dengan film masukan.

### Hasil Pengamatan

Berdasarkan pengujian terhadap 10 film, sistem menunjukkan hasil yang cukup menjanjikan pada sejumlah contoh:

* **The Dark Knight:** merekomendasikan *The Dark Knight Rises* dan *Batman Begins* pada posisi teratas.
* **Finding Nemo:** merekomendasikan *Finding Dory* serta film animasi keluarga lainnya.
* **The Godfather:** merekomendasikan *The Godfather: Part II* dan *The Godfather: Part III*.
* **Toy Story:** merekomendasikan *Toy Story 3* dan *Toy Story 2*.
* **The Conjuring:** merekomendasikan *The Conjuring 2* dan sejumlah film horor.
* **The Matrix:** merekomendasikan dua film sekuelnya pada posisi teratas.
* **Minions:** merekomendasikan beberapa film dalam waralaba *Despicable Me*.
* **Home Alone:** merekomendasikan beberapa film dari koleksi yang sama.

Pada film *Titanic*, rekomendasi didominasi film bergenre drama dan romansa. Sementara itu, rekomendasi untuk *The Shawshank Redemption* mencakup beberapa film bergenre crime dan drama. Kesamaan genre tersebut belum tentu menunjukkan kesamaan alur cerita secara keseluruhan.

### Interpretasi

Hasil pengamatan menunjukkan bahwa kombinasi fitur genre, overview, tagline, dan koleksi film dapat menghasilkan rekomendasi yang memiliki kemiripan konten. Informasi koleksi film tampak membantu dalam menempatkan sekuel atau film dari waralaba yang sama pada posisi teratas.

Namun, evaluasi ini masih bersifat kualitatif. Pengamatan terhadap sejumlah contoh belum cukup untuk menyimpulkan bahwa sistem memiliki tingkat relevansi yang tinggi pada seluruh dataset.

### Keterbatasan

1. Sistem hanya memanfaatkan metadata dan konten film yang tersedia pada dataset.
2. Kualitas rekomendasi bergantung pada kelengkapan dan representasi teks setiap fitur.
3. Bobot fitur yang digunakan merupakan konfigurasi awal eksperimental dan belum dioptimalkan secara sistematis.
4. Evaluasi relevansi masih dilakukan secara kualitatif, belum menggunakan ground truth atau metrik evaluasi rekomendasi yang terukur.
5. Kemiripan berdasarkan teks tidak selalu mencerminkan kesamaan tema, alur cerita, atau preferensi pengguna.

### Kesimpulan

Content-Based Movie Recommender berhasil menghasilkan rekomendasi berdasarkan kemiripan metadata film dengan pendekatan TF-IDF dan cosine similarity. Hasil awal menunjukkan bahwa sistem dapat mengenali beberapa hubungan yang masuk akal, terutama berdasarkan genre dan koleksi film. Evaluasi lanjutan diperlukan untuk mengukur relevansi secara lebih objektif dan menentukan konfigurasi fitur yang lebih baik.